language: node_js
node_js:
- '7'
deploy:
  - provider: npm
    email: n.moraes.dantas@gmail.com
    api_key: $NPM_API_KEY
  - provider: openshift
    user: n.moraes.dantas@gmail.com
    password: $OPEN_SHIFT_PASSWORD
    domain: https://manage.openshift.com
    app:
      master: swt-user-manager
cache:
  directories:
  - node_modules
before_install:
- npm rm --save-dev
- test ! -d node_modules || npm prune
- test ! -d node_modules || npm rebuild
