language: node_js
node_js:
- '7'
deploy:
  - provider: npm
    email: n.moraes.dantas@gmail.com
    api_key: $NPM_API_KEY
cache:
  directories:
  - node_modules
before_install:
- npm rm --save-dev
- test ! -d node_modules || npm prune
- test ! -d node_modules || npm rebuild
